Dashboard: Add 'run-nginx.sh' script to update prebuilt docker containers when running
This enables us to use the same container for different API urls, cookie names, and cookie domains.

diff --git a/apps/tergite-dashboard/Dockerfile b/apps/tergite-dashboard/Dockerfile
--- a/apps/tergite-dashboard/Dockerfile
+++ b/apps/tergite-dashboard/Dockerfile
@@ -23,9 +23,24 @@ RUN VITE_COOKIE_DOMAIN=$(cat ./mss-config.toml | ./dasel -r toml 'auth.cookie_do
 RUN VITE_COOKIE_NAME=$(cat ./mss-config.toml | ./dasel -r toml 'auth.cookie_name')
 
 # create and fill the local production .env file
-RUN if [ -n "$VITE_API_BASE_URL" ]; then echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> .env.production.local; else echo "VITE_API_BASE_URL is required"; exit 1; fi;
-RUN if [ -n "$VITE_COOKIE_DOMAIN" ]; then echo "VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN" >> .env.production.local; fi;
-RUN if [ -n "$VITE_COOKIE_NAME" ]; then echo "VITE_COOKIE_NAME=$VITE_COOKIE_NAME" >> .env.production.local; fi;
+RUN if [ -n "$VITE_API_BASE_URL" ]; \
+    then echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> .env.production.local; \
+    else \
+        echo "VITE_API_BASE_URL is required"; \
+        exit 1; \
+    fi;
+RUN if [ -n "$VITE_COOKIE_DOMAIN" ]; \
+    then echo "VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN" >> .env.production.local; \
+    else \
+        echo "auth.cookie_domain is required in ${MSS_CONFIG_FILE}";\
+        exit 1;\
+    fi;
+RUN if [ -n "$VITE_COOKIE_NAME" ];\
+    then echo "VITE_COOKIE_NAME=$VITE_COOKIE_NAME" >> .env.production.local;\
+    else\
+        echo "auth.cookie_name is required in ${MSS_CONFIG_FILE}";\
+        exit 1;\
+    fi;
 
 RUN npm run build
 
@@ -33,8 +48,19 @@ RUN npm run build
 FROM nginx:1.27.1-alpine-slim as prod
 
 COPY --from=build /app/dist /usr/share/nginx/html
+COPY --from=build /app/.env.production.local /etc/nginx/.env.local
 COPY nginx.conf /etc/nginx/nginx.conf
+COPY run-nginx.sh /usr/sbin/run-nginx
+
+RUN chmod +x /usr/sbin/run-nginx
 
 EXPOSE 80/tcp
 
-CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
+# expected env variables
+ENV COOKIE_DOMAIN=""
+ENV COOKIE_NAME=""
+ENV API_BASE_URL=""
+
+ENTRYPOINT [ "/usr/sbin/run-nginx" ]
+
+CMD ["-g", "daemon off;"]
