Dashboard: errors while running dashboard docker image

diff --git a/apps/tergite-dashboard/Dockerfile b/apps/tergite-dashboard/Dockerfile
--- a/apps/tergite-dashboard/Dockerfile
+++ b/apps/tergite-dashboard/Dockerfile
@@ -1,12 +1,14 @@
 #Building the react app
-FROM node:20-alpine as build
+FROM node:20-alpine AS build
 
 WORKDIR /app
 ARG MSS_CONFIG_FILE
 ARG VITE_API_BASE_URL
+ARG VITE_COOKIE_DOMAIN
+ARG VITE_COOKIE_NAME
 
 COPY package*.json ./
-COPY --from=parent-folder $MSS_CONFIG_FILE ./mss-config.toml
+COPY --from=parent-folder "$MSS_CONFIG_FILE"* ./
 
 RUN npm ci
 
@@ -16,36 +18,47 @@ RUN apk --no-cache add curl
 
 # Get a TOML reader CLI 'dasel'
 RUN curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
-RUN 
 
-# read auth config
-RUN VITE_COOKIE_DOMAIN=$(cat ./mss-config.toml | ./dasel -r toml 'auth.cookie_domain')
-RUN VITE_COOKIE_NAME=$(cat ./mss-config.toml | ./dasel -r toml 'auth.cookie_name')
-
-# create and fill the local production .env file
-RUN if [ -n "$VITE_API_BASE_URL" ]; \
+# If $MSS_CONFIG_FILE was copied, update .env.production.local
+RUN \
+    cookie_domain=""; \
+    cookie_name=""; \
+    if [ -f "$MSS_CONFIG_FILE" ]; then \
+        # read the variables from the toml config file
+        cookie_domain=$(cat "$MSS_CONFIG_FILE" | ./dasel -r toml 'auth.cookie_domain');\
+        cookie_name=$(cat "$MSS_CONFIG_FILE" | ./dasel -r toml 'auth.cookie_name');\
+    fi; \
+    # add them to the .env.production.local file
+    # cookie domain; try build arg VITE_COOKIE_DOMAIN first before falling back to value from MSS_CONFIG_FILE
+    if [ -n "$VITE_COOKIE_DOMAIN" ]; then \
+        echo "VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN" >> .env.production.local; \
+    elif [ -n "$cookie_domain" ]; then \
+        echo "VITE_COOKIE_DOMAIN=$cookie_domain" >> .env.production.local; \
+    else \
+        echo "auth.cookie_domain is required in ${MSS_CONFIG_FILE} or you set --build-arg VITE_COOKIE_DOMAIN=...";\
+        exit 1;\
+    fi;\
+    # cookie name; try build arg VITE_COOKIE_NAME first before falling back to value from MSS_CONFIG_FILE
+    if [ -n "$VITE_COOKIE_NAME" ]; then \
+        echo "VITE_COOKIE_NAME=$VITE_COOKIE_NAME" >> .env.production.local; \
+    elif [ -n "$cookie_name" ]; then \
+        echo "VITE_COOKIE_NAME=$cookie_name" >> .env.production.local; \
+    else \
+        echo "auth.cookie_name is required in ${MSS_CONFIG_FILE} or you set --build-arg VITE_COOKIE_NAME=...";\
+        exit 1;\
+    fi; \
+    # VITE_API_BASE_URL build arg
+    if [ -n "$VITE_API_BASE_URL" ]; \
     then echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> .env.production.local; \
     else \
         echo "VITE_API_BASE_URL is required"; \
         exit 1; \
-    fi;
-RUN if [ -n "$VITE_COOKIE_DOMAIN" ]; \
-    then echo "VITE_COOKIE_DOMAIN=$VITE_COOKIE_DOMAIN" >> .env.production.local; \
-    else \
-        echo "auth.cookie_domain is required in ${MSS_CONFIG_FILE}";\
-        exit 1;\
-    fi;
-RUN if [ -n "$VITE_COOKIE_NAME" ];\
-    then echo "VITE_COOKIE_NAME=$VITE_COOKIE_NAME" >> .env.production.local;\
-    else\
-        echo "auth.cookie_name is required in ${MSS_CONFIG_FILE}";\
-        exit 1;\
-    fi;
+    fi; 
 
 RUN npm run build
 
 # Building the final image
-FROM nginx:1.27.1-alpine-slim as prod
+FROM nginx:1.27.1-alpine-slim AS prod
 
 COPY --from=build /app/dist /usr/share/nginx/html
 COPY --from=build /app/.env.production.local /etc/nginx/.env.local
